{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"filePath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameramedia\/filepath"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameramedia\/filepath"]}],"identifier":{"url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMedia\/filePath","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"metadata":{"navigatorTitle":[{"text":"filePath","kind":"identifier"}],"role":"symbol","title":"filePath","roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"TruvideoSdkCamera"}],"externalID":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraMedia(py)filePath","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"filePath","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMedia"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraMedia/filePath":{"kind":"symbol","role":"symbol","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameramedia\/filepath","abstract":[],"title":"filePath","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"filePath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"text":"filePath","kind":"identifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMedia\/filePath","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraMedia":{"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TruvideoSdkCameraMedia","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameramedia","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraMedia"}],"type":"topic","title":"TruvideoSdkCameraMedia","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMedia","kind":"symbol","role":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"type":"topic","title":"TruvideoSdkCamera","url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}],"kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"filePath","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"filePath"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"filePath","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"value":"filePath","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMedia~1filePath\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMedia~1filePath\/fragments","value":[{"kind":"identifier","text":"filePath"}]},{"op":"replace","value":"TruvideoSdkCameraMedia","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMedia\/title"},{"op":"replace","value":[{"text":"TruvideoSdkCameraMedia","kind":"identifier"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMedia\/fragments"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMedia\/navigatorTitle","value":[{"text":"TruvideoSdkCameraMedia","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}