{"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SwiftUICore","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SwiftUICore\/View"]]},"identifier":{"url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SwiftUICore\/View\/presentTruvideoSdkARCameraView(isPresented:preset:onComplete:)","interfaceLanguage":"swift"},"abstract":[{"text":"Present the AR camera view over the full screen","type":"text"}],"variants":[{"paths":["\/documentation\/truvideosdkcamera\/swiftuicore\/view\/presenttruvideosdkarcameraview(ispresented:preset:oncomplete:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"presentTruvideoSdkARCameraView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"isPresented","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI7BindingV","text":"Binding"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"preset"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkARCameraConfiguration","text":"TruvideoSdkARCameraConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"onComplete"},{"kind":"text","text":": ("},{"text":"TruvideoSdkCameraResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResult"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"text":"View","preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier"}],"symbolKind":"method","title":"presentTruvideoSdkARCameraView(isPresented:preset:onComplete:)","modules":[{"name":"TruvideoSdkCamera","relatedModules":["SwiftUICore"]}],"role":"symbol","extendedModule":"SwiftUICore","externalID":"s:7SwiftUI4ViewP17TruvideoSdkCameraE07presentde8ARCameraC011isPresented6preset10onCompleteQrAA7BindingVySbG_AD0deH13ConfigurationCyAD0deF6ResultCctF","roleHeading":"Instance Method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"presentTruvideoSdkARCameraView","kind":"identifier"},{"kind":"text","text":"("},{"text":"isPresented","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI7BindingV","kind":"typeIdentifier","text":"Binding"},{"kind":"text","text":"<"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":">, "},{"text":"preset","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkARCameraConfiguration","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkARCameraConfiguration","text":"TruvideoSdkARCameraConfiguration"},{"kind":"text","text":" = .init(flashMode: .off, mode: .videoAndPicture()), "},{"text":"onComplete","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResult","text":"TruvideoSdkCameraResult"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI4ViewP","text":"View","kind":"typeIdentifier"},{"text":"\n","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A boolean indicating whether the preview is presented."}]}],"name":"isPresented"},{"content":[{"type":"paragraph","inlineContent":[{"text":"A preset to configure de AR Camera","type":"text"}]}],"name":"preset"},{"name":"onComplete","content":[{"inlineContent":[{"type":"text","text":"A callback with the recording result"}],"type":"paragraph"}]}]},{"content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"inlineContent":[{"text":"The modified view.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/SwiftUICore":{"title":"SwiftUICore","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SwiftUICore","type":"topic","role":"collection","kind":"symbol","abstract":[],"url":"\/documentation\/truvideosdkcamera\/swiftuicore"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkARCameraConfiguration":{"role":"symbol","url":"\/documentation\/truvideosdkcamera\/truvideosdkarcameraconfiguration","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkARCameraConfiguration"}],"title":"TruvideoSdkARCameraConfiguration","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkARCameraConfiguration","abstract":[{"text":"A configuration object for setting up the AR Camera in ","type":"text"},{"code":"TruvideoSdkCamera","type":"codeVoice"},{"text":".","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TruvideoSdkARCameraConfiguration"}],"kind":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/SwiftUICore/View/presentTruvideoSdkARCameraView(isPresented:preset:onComplete:)":{"title":"presentTruvideoSdkARCameraView(isPresented:preset:onComplete:)","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SwiftUICore\/View\/presentTruvideoSdkARCameraView(isPresented:preset:onComplete:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"presentTruvideoSdkARCameraView","kind":"identifier"},{"kind":"text","text":"("},{"text":"isPresented","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7SwiftUI7BindingV","text":"Binding","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"preset","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkARCameraConfiguration","kind":"typeIdentifier","text":"TruvideoSdkARCameraConfiguration"},{"kind":"text","text":", "},{"text":"onComplete","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResult","kind":"typeIdentifier","text":"TruvideoSdkCameraResult"},{"kind":"text","text":") -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI4ViewP","text":"View","kind":"typeIdentifier"}],"kind":"symbol","abstract":[{"text":"Present the AR camera view over the full screen","type":"text"}],"url":"\/documentation\/truvideosdkcamera\/swiftuicore\/view\/presenttruvideosdkarcameraview(ispresented:preset:oncomplete:)"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/SwiftUICore/View":{"role":"symbol","url":"\/documentation\/truvideosdkcamera\/swiftuicore\/view","navigatorTitle":[{"text":"View","kind":"identifier"}],"title":"View","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SwiftUICore\/View","abstract":[],"type":"topic","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"View","preciseIdentifier":"s:7SwiftUI4ViewP"}],"kind":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"type":"topic","title":"TruvideoSdkCamera","url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}],"kind":"symbol","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraResult":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TruvideoSdkCameraResult","kind":"identifier"}],"role":"symbol","abstract":[{"text":"A result of the recording session.","type":"text"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResult","kind":"symbol","title":"TruvideoSdkCameraResult","navigatorTitle":[{"text":"TruvideoSdkCameraResult","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraresult"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkARCameraConfiguration\/title","value":"TruvideoSdkARCameraConfiguration"},{"value":[{"text":"TruvideoSdkARCameraConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkARCameraConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkARCameraConfiguration\/navigatorTitle","value":[{"text":"TruvideoSdkARCameraConfiguration","kind":"identifier"}]},{"value":"TruvideoSdkCameraResult","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResult\/title","op":"replace"},{"value":[{"text":"TruvideoSdkCameraResult","kind":"identifier"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResult\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"TruvideoSdkCameraResult"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResult\/navigatorTitle"}]}]}