{"metadata":{"title":"presentTruvideoSdkScannerCameraView(isPresented:preset:onComplete:)","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"presentTruvideoSdkScannerCameraView","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"isPresented"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI7BindingV","text":"Binding","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"preset"},{"text":": ","kind":"text"},{"text":"TruvideoSdkScannerCameraConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkScannerCameraConfiguration"},{"text":", ","kind":"text"},{"text":"onComplete","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TruvideoSdkScannerCameraViewCallback","kind":"typeIdentifier","preciseIdentifier":"s:17TruvideoSdkCamera0ab7ScannerC12ViewCallbacka"},{"text":") -> ","kind":"text"},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"}],"modules":[{"name":"TruvideoSdkCamera","relatedModules":["SwiftUICore"]}],"extendedModule":"SwiftUICore","roleHeading":"Instance Method","role":"symbol","externalID":"s:7SwiftUI4ViewP17TruvideoSdkCameraE07presentde7ScannerfC011isPresented6preset10onCompleteQrAA7BindingVySbG_AD0dehF13ConfigurationCyAD0defH4CodeCSgctF"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SwiftUICore\/View\/presentTruvideoSdkScannerCameraView(isPresented:preset:onComplete:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"presentTruvideoSdkScannerCameraView"},{"text":"(","kind":"text"},{"text":"isPresented","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Binding","preciseIdentifier":"s:7SwiftUI7BindingV","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":">, ","kind":"text"},{"text":"preset","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TruvideoSdkScannerCameraConfiguration","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkScannerCameraConfiguration","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkScannerCameraConfiguration","kind":"typeIdentifier"},{"kind":"text","text":" = .init(\n            flashMode: .off,\n            orientation: nil\n        ), "},{"text":"onComplete","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" ","kind":"text"},{"text":"TruvideoSdkScannerCameraViewCallback","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkScannerCameraViewCallback","kind":"typeIdentifier","preciseIdentifier":"s:17TruvideoSdkCamera0ab7ScannerC12ViewCallbacka"},{"text":") -> ","kind":"text"},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"preciseIdentifier":"s:7SwiftUI4ViewP","text":"View","kind":"typeIdentifier"},{"kind":"text","text":"\n"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"isPresented","content":[{"inlineContent":[{"text":"A boolean indicating whether the preview is presented.","type":"text"}],"type":"paragraph"}]},{"name":"onComplete","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A callback with the recording result"}]}]}],"kind":"parameters"},{"content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"inlineContent":[{"type":"text","text":"The modified view"}],"type":"paragraph"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/swiftuicore\/view\/presenttruvideosdkscannercameraview(ispresented:preset:oncomplete:)"]}],"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SwiftUICore","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SwiftUICore\/View"]]},"abstract":[{"type":"text","text":"Present the camera view over the full screen"}],"sections":[],"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/SwiftUICore/View":{"role":"symbol","url":"\/documentation\/truvideosdkcamera\/swiftuicore\/view","navigatorTitle":[{"text":"View","kind":"identifier"}],"title":"View","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SwiftUICore\/View","abstract":[],"type":"topic","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"View","preciseIdentifier":"s:7SwiftUI4ViewP"}],"kind":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkScannerCameraConfiguration":{"abstract":[{"text":"Configuration settings for the ","type":"text"},{"inlineContent":[{"text":"Truvideo Scanner Camera","type":"text"}],"type":"strong"},{"text":".","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkScannerCameraConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TruvideoSdkScannerCameraConfiguration","kind":"identifier"}],"title":"TruvideoSdkScannerCameraConfiguration","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkScannerCameraConfiguration"}],"kind":"symbol","url":"\/documentation\/truvideosdkcamera\/truvideosdkscannercameraconfiguration"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/SwiftUICore":{"title":"SwiftUICore","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SwiftUICore","type":"topic","role":"collection","kind":"symbol","abstract":[],"url":"\/documentation\/truvideosdkcamera\/swiftuicore"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/SwiftUICore/View/presentTruvideoSdkScannerCameraView(isPresented:preset:onComplete:)":{"kind":"symbol","type":"topic","abstract":[{"text":"Present the camera view over the full screen","type":"text"}],"url":"\/documentation\/truvideosdkcamera\/swiftuicore\/view\/presenttruvideosdkscannercameraview(ispresented:preset:oncomplete:)","title":"presentTruvideoSdkScannerCameraView(isPresented:preset:onComplete:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"presentTruvideoSdkScannerCameraView","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"isPresented"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7SwiftUI7BindingV","kind":"typeIdentifier","text":"Binding"},{"text":"<","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"preset","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TruvideoSdkScannerCameraConfiguration","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkScannerCameraConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"onComplete"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TruvideoSdkScannerCameraViewCallback","preciseIdentifier":"s:17TruvideoSdkCamera0ab7ScannerC12ViewCallbacka"},{"text":") -> ","kind":"text"},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"text":"View","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SwiftUICore\/View\/presentTruvideoSdkScannerCameraView(isPresented:preset:onComplete:)"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkScannerCameraViewCallback":{"type":"topic","url":"\/documentation\/truvideosdkcamera\/truvideosdkscannercameraviewcallback","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkScannerCameraViewCallback"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkScannerCameraViewCallback","kind":"symbol","title":"TruvideoSdkScannerCameraViewCallback","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"TruvideoSdkScannerCameraViewCallback","kind":"identifier"}],"abstract":[{"type":"text","text":"A callback function that handles the result of a barcode or QR code scan."}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"type":"topic","title":"TruvideoSdkCamera","url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}],"kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkScannerCameraConfiguration\/title","op":"replace","value":"TruvideoSdkScannerCameraConfiguration"},{"value":[{"kind":"identifier","text":"TruvideoSdkScannerCameraConfiguration"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkScannerCameraConfiguration\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkScannerCameraConfiguration\/navigatorTitle","value":[{"text":"TruvideoSdkScannerCameraConfiguration","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}