{"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResult(py)media","modules":[{"name":"TruvideoSdkCamera"}],"title":"media","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"media","kind":"identifier"},{"text":": [","kind":"text"},{"text":"TruvideoSdkCameraMedia","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraMedia","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"media"}],"symbolKind":"property"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"media","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraMedia","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMedia","kind":"typeIdentifier","text":"TruvideoSdkCameraMedia"},{"kind":"text","text":"]"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResult\/media","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameraresult\/media"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameraresult\/media"]}],"abstract":[{"type":"text","text":"The media recorded during the session."}],"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResult"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"type":"topic","title":"TruvideoSdkCamera","url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}],"kind":"symbol","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraResult/media":{"role":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResult\/media","navigatorTitle":[{"kind":"identifier","text":"media"}],"abstract":[{"text":"The media recorded during the session.","type":"text"}],"title":"media","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"media","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraMedia","text":"TruvideoSdkCameraMedia","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraresult\/media","type":"topic","kind":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraResult":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TruvideoSdkCameraResult","kind":"identifier"}],"role":"symbol","abstract":[{"text":"A result of the recording session.","type":"text"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResult","kind":"symbol","title":"TruvideoSdkCameraResult","navigatorTitle":[{"text":"TruvideoSdkCameraResult","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraresult"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraMedia":{"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TruvideoSdkCameraMedia","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameramedia","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraMedia"}],"type":"topic","title":"TruvideoSdkCameraMedia","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMedia","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"media","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"media"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<TruvideoSdkCameraMedia *>"},{"text":" * ","kind":"text"},{"text":"media","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"media","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResult~1media\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResult~1media\/fragments","value":[{"text":"media","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"TruvideoSdkCameraResult","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResult\/title"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResult\/fragments","value":[{"text":"TruvideoSdkCameraResult","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResult\/navigatorTitle","value":[{"text":"TruvideoSdkCameraResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMedia\/title","value":"TruvideoSdkCameraMedia"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMedia\/fragments","op":"replace","value":[{"text":"TruvideoSdkCameraMedia","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMedia\/navigatorTitle","op":"replace","value":[{"text":"TruvideoSdkCameraMedia","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}