{"metadata":{"symbolKind":"init","modules":[{"name":"TruvideoSdkCamera"}],"externalID":"s:So16InstanceUniformsa11modelMatrixABSo13simd_float4x4a_tcfc","role":"symbol","title":"init(modelMatrix:)","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"modelMatrix"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@matrix_float4x4","text":"matrix_float4x4","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/instanceuniforms\/init(modelmatrix:)"]}],"identifier":{"url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/InstanceUniforms\/init(modelMatrix:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"modelMatrix"},{"kind":"text","text":": "},{"text":"matrix_float4x4","kind":"typeIdentifier","preciseIdentifier":"c:@T@matrix_float4x4"},{"text":")","kind":"text"}]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/InstanceUniforms"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/InstanceUniforms/init(modelMatrix:)":{"url":"\/documentation\/truvideosdkcamera\/instanceuniforms\/init(modelmatrix:)","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/InstanceUniforms\/init(modelMatrix:)","title":"init(modelMatrix:)","type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"modelMatrix"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@matrix_float4x4","text":"matrix_float4x4"},{"text":")","kind":"text"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/InstanceUniforms":{"role":"symbol","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InstanceUniforms","kind":"identifier"}],"navigatorTitle":[{"text":"InstanceUniforms","kind":"identifier"}],"title":"InstanceUniforms","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/InstanceUniforms","type":"topic","abstract":[],"url":"\/documentation\/truvideosdkcamera\/instanceuniforms"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"type":"topic","title":"TruvideoSdkCamera","url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}],"kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1InstanceUniforms\/title","op":"replace","value":"InstanceUniforms"},{"value":[{"text":"","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1InstanceUniforms\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1InstanceUniforms\/navigatorTitle","value":[{"text":"InstanceUniforms","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}