{"metadata":{"roleHeading":"Instance Property","modules":[{"name":"TruvideoSdkCamera"}],"role":"symbol","title":"directionalLightDirection","externalID":"c:@SA@SharedUniforms@FI@directionalLightDirection","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"directionalLightDirection","kind":"identifier"},{"kind":"text","text":": "},{"text":"vector_float3","preciseIdentifier":"c:@T@vector_float3","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"directionalLightDirection","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SharedUniforms"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"directionalLightDirection"},{"kind":"text","text":": "},{"text":"vector_float3","preciseIdentifier":"c:@T@vector_float3","kind":"typeIdentifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/shareduniforms\/directionallightdirection"]},{"paths":["\/documentation\/truvideosdkcamera\/shareduniforms\/directionallightdirection"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SharedUniforms\/directionalLightDirection"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/SharedUniforms/directionalLightDirection":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SharedUniforms\/directionalLightDirection","role":"symbol","title":"directionalLightDirection","kind":"symbol","url":"\/documentation\/truvideosdkcamera\/shareduniforms\/directionallightdirection","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"directionalLightDirection","kind":"identifier"},{"kind":"text","text":": "},{"text":"vector_float3","kind":"typeIdentifier","preciseIdentifier":"c:@T@vector_float3"}],"navigatorTitle":[{"kind":"identifier","text":"directionalLightDirection"}],"abstract":[]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/SharedUniforms":{"type":"topic","title":"SharedUniforms","role":"symbol","abstract":[],"url":"\/documentation\/truvideosdkcamera\/shareduniforms","navigatorTitle":[{"text":"SharedUniforms","kind":"identifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SharedUniforms","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"SharedUniforms","kind":"identifier"}],"kind":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"type":"topic","title":"TruvideoSdkCamera","url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}],"kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"directionalLightDirection"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"directionalLightDirection"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"typeIdentifier","text":"vector_float3","preciseIdentifier":"c:@T@vector_float3"},{"text":" ","kind":"text"},{"text":"directionalLightDirection","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1SharedUniforms~1directionalLightDirection\/title","value":"directionalLightDirection","op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1SharedUniforms~1directionalLightDirection\/fragments","value":[{"text":"directionalLightDirection","kind":"identifier"}],"op":"replace"},{"value":"SharedUniforms","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1SharedUniforms\/title"},{"value":[{"text":"","kind":"identifier"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1SharedUniforms\/fragments","op":"replace"},{"op":"replace","value":[{"text":"SharedUniforms","kind":"identifier"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1SharedUniforms\/navigatorTitle"}]}]}