{"metadata":{"externalID":"s:SLsE3zzlopys16PartialRangeUpToVyxGxFZ::SYNTHESIZED::c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResolution","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"..<"},{"text":" ","kind":"text"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"PartialRangeUpTo","preciseIdentifier":"s:s16PartialRangeUpToV"},{"kind":"text","text":"<"},{"text":"Self","kind":"typeIdentifier"},{"text":">","kind":"text"}],"role":"symbol","title":"..<(_:)","roleHeading":"Operator","extendedModule":"Swift","symbolKind":"op","modules":[{"name":"TruvideoSdkCamera","relatedModules":["Swift"]}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameraresolution\/'.._(_:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"..<"},{"text":" ","kind":"text"},{"kind":"text","text":"("},{"kind":"internalParam","text":"maximum"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"PartialRangeUpTo","preciseIdentifier":"s:s16PartialRangeUpToV"},{"text":"<","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":">"}],"platforms":["iOS"]}]}],"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResolution\/.._(_:)"},"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResolution","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResolution\/Comparable-Implementations"]]},"abstract":[{"type":"text","text":"Inherited from "},{"code":"Comparable...<(_:)","type":"codeVoice"},{"type":"text","text":"."}],"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"type":"topic","title":"TruvideoSdkCamera","url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}],"kind":"symbol","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraResolution/.._(_:)":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResolution\/.._(_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"..<","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s16PartialRangeUpToV","text":"PartialRangeUpTo"},{"text":"<","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":">"}],"role":"symbol","abstract":[],"title":"..<(_:)","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraresolution\/'.._(_:)","kind":"symbol","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraResolution/Comparable-Implementations":{"type":"topic","role":"collectionGroup","title":"Comparable Implementations","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraresolution\/comparable-implementations","abstract":[],"kind":"article","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResolution\/Comparable-Implementations"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraResolution":{"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraresolution","type":"topic","kind":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResolution","navigatorTitle":[{"text":"TruvideoSdkCameraResolution","kind":"identifier"}],"title":"TruvideoSdkCameraResolution","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TruvideoSdkCameraResolution","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"TruvideoSdkCameraResolution","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResolution\/title"},{"op":"replace","value":[{"kind":"identifier","text":"TruvideoSdkCameraResolution"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResolution\/fragments"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResolution\/navigatorTitle","op":"replace","value":[{"text":"TruvideoSdkCameraResolution","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}