{"abstract":[{"type":"text","text":"Present the camera view over the full screen"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/swiftuicore\/view\/presenttruvideosdkcameraview(ispresented:preset:oncomplete:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"title":"presentTruvideoSdkCameraView(isPresented:preset:onComplete:)","role":"symbol","modules":[{"name":"TruvideoSdkCamera","relatedModules":["SwiftUICore"]}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"presentTruvideoSdkCameraView","kind":"identifier"},{"kind":"text","text":"("},{"text":"isPresented","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI7BindingV","text":"Binding"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"preset"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraConfiguration","text":"TruvideoSdkCameraConfiguration","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"onComplete","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"TruvideoSdkCameraResult","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResult","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"text":"View","preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier"}],"roleHeading":"Instance Method","extendedModule":"SwiftUICore","externalID":"s:7SwiftUI4ViewP17TruvideoSdkCameraE07presentdefC011isPresented6preset10onCompleteQrAA7BindingVySbG_AD0deF13ConfigurationCyAD0deF6ResultCctF"},"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SwiftUICore","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SwiftUICore\/View"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SwiftUICore\/View\/presentTruvideoSdkCameraView(isPresented:preset:onComplete:)"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"presentTruvideoSdkCameraView","kind":"identifier"},{"kind":"text","text":"("},{"text":"isPresented","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI7BindingV","text":"Binding"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"preset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraConfiguration","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraConfiguration","text":"TruvideoSdkCameraConfiguration"},{"text":" = .init(\n            lensFacing: .back,\n            flashMode: .off,\n            orientation: nil,\n            outputPath: \"\",\n            frontResolutions: [],\n            frontResolution: nil,\n            backResolutions: [],\n            backResolution: nil,\n            mode: .videoAndPicture()\n        ), ","kind":"text"},{"text":"onComplete","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"text":" (","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResult","text":"TruvideoSdkCameraResult","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResult"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"text":" ","kind":"text"},{"text":"View","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP"},{"kind":"text","text":"\n"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A boolean indicating whether the preview is presented."}]}],"name":"isPresented"},{"name":"onComplete","content":[{"inlineContent":[{"type":"text","text":"A callback with the recording result"}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The modified view"}]}]}],"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/SwiftUICore":{"title":"SwiftUICore","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SwiftUICore","type":"topic","role":"collection","kind":"symbol","abstract":[],"url":"\/documentation\/truvideosdkcamera\/swiftuicore"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraResult":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TruvideoSdkCameraResult","kind":"identifier"}],"role":"symbol","abstract":[{"text":"A result of the recording session.","type":"text"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResult","kind":"symbol","title":"TruvideoSdkCameraResult","navigatorTitle":[{"text":"TruvideoSdkCameraResult","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraresult"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/SwiftUICore/View":{"role":"symbol","url":"\/documentation\/truvideosdkcamera\/swiftuicore\/view","navigatorTitle":[{"text":"View","kind":"identifier"}],"title":"View","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SwiftUICore\/View","abstract":[],"type":"topic","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"View","preciseIdentifier":"s:7SwiftUI4ViewP"}],"kind":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"type":"topic","title":"TruvideoSdkCamera","url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}],"kind":"symbol","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/SwiftUICore/View/presentTruvideoSdkCameraView(isPresented:preset:onComplete:)":{"url":"\/documentation\/truvideosdkcamera\/swiftuicore\/view\/presenttruvideosdkcameraview(ispresented:preset:oncomplete:)","type":"topic","role":"symbol","title":"presentTruvideoSdkCameraView(isPresented:preset:onComplete:)","abstract":[{"type":"text","text":"Present the camera view over the full screen"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/SwiftUICore\/View\/presentTruvideoSdkCameraView(isPresented:preset:onComplete:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"presentTruvideoSdkCameraView"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"isPresented"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Binding","preciseIdentifier":"s:7SwiftUI7BindingV"},{"text":"<","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":">, "},{"text":"preset","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraConfiguration","text":"TruvideoSdkCameraConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onComplete"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResult","kind":"typeIdentifier","text":"TruvideoSdkCameraResult"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":") -> ","kind":"text"},{"kind":"keyword","text":"some"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"}],"kind":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraConfiguration":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraConfiguration"}],"type":"topic","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraConfiguration","title":"TruvideoSdkCameraConfiguration","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"A configuration object for setting up the camera in "},{"type":"codeVoice","code":"TruvideoSdkCamera"},{"text":".","type":"text"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraconfiguration"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResult\/title","value":"TruvideoSdkCameraResult","op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResult\/fragments","op":"replace","value":[{"text":"TruvideoSdkCameraResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResult\/navigatorTitle","value":[{"text":"TruvideoSdkCameraResult","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraConfiguration\/title","value":"TruvideoSdkCameraConfiguration","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraConfiguration\/fragments","value":[{"text":"TruvideoSdkCameraConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TruvideoSdkCameraConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}