{"metadata":{"externalID":"c:@M@TruvideoSdkCamera@objc(pl)TruvideoSdkCameraAppDelegate","role":"symbol","symbolKind":"protocol","modules":[{"name":"TruvideoSdkCamera"}],"roleHeading":"Protocol","title":"TruvideoSdkCameraAppDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TruvideoSdkCameraAppDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraAppDelegate"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TruvideoSdkCameraAppDelegate","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIApplicationDelegate","preciseIdentifier":"c:objc(pl)UIApplicationDelegate"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"type":"heading","text":"Overview","anchor":"overview","level":2},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"TruvideoSdkCameraAppDelegate"},{"type":"text","text":" extends "},{"type":"codeVoice","code":"UIApplicationDelegate"},{"type":"text","text":" and provides control over "},{"inlineContent":[{"text":"interface orientation lock","type":"text"}],"type":"strong"},{"type":"text","text":" settings."}]},{"anchor":"Overview","level":2,"text":"Overview","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This protocol is responsible for:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Managing the orientation lock"}]},{"text":" for the camera.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"inlineContent":[{"text":"Defining supported interface orientations","type":"text"}],"type":"strong"},{"type":"text","text":" for the application."}]}]}]},{"type":"heading","anchor":"Example-Usage","text":"Example Usage","level":2},{"code":["class AppDelegate: UIResponder, TruvideoSdkCameraAppDelegate {","    var orientationLock: UIInterfaceOrientationMask = .portrait","","    func application(","        _ application: UIApplication,","        supportedInterfaceOrientationsFor window: UIWindow?","    ) -> UIInterfaceOrientationMask {","        return orientationLock","    }","}"],"syntax":"swift","type":"codeListing"}]}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraAppDelegate\/orientationLock"],"anchor":"Instance-Properties","title":"Instance Properties"},{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraAppDelegate\/application(_:supportedInterfaceOrientationsFor:)"],"generated":true}],"identifier":{"url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraAppDelegate","interfaceLanguage":"swift"},"kind":"symbol","relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/objc(pl)NSObject","doc:\/\/com.truvideo.TruvideoSdkCamera\/objc(pl)UIApplicationDelegate"],"kind":"relationships","title":"Inherits From"}],"variants":[{"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameraappdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameraappdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Defines the application delegate for handling camera-related configurations."}],"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"type":"topic","title":"TruvideoSdkCamera","url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}],"kind":"symbol","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/objc(pl)NSObject":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.truvideo.TruvideoSdkCamera/objc(pl)UIApplicationDelegate":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/objc(pl)UIApplicationDelegate","title":"UIApplicationDelegate","type":"unresolvable"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraAppDelegate/orientationLock":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"orientationLock","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIInterfaceOrientationMask","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIInterfaceOrientationMask"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"orientationLock"}],"title":"orientationLock","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraappdelegate\/orientationlock","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraAppDelegate\/orientationLock","type":"topic","kind":"symbol","required":true,"abstract":[{"text":"The current orientation lock for the application.","type":"text"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraAppDelegate":{"abstract":[{"text":"Defines the application delegate for handling camera-related configurations.","type":"text"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraAppDelegate","title":"TruvideoSdkCameraAppDelegate","kind":"symbol","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraappdelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraAppDelegate"}],"navigatorTitle":[{"text":"TruvideoSdkCameraAppDelegate","kind":"identifier"}],"type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraAppDelegate/application(_:supportedInterfaceOrientationsFor:)":{"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraappdelegate\/application(_:supportedinterfaceorientationsfor:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"application","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"supportedInterfaceOrientationsFor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIWindow","kind":"typeIdentifier","text":"UIWindow"},{"text":"?) -> ","kind":"text"},{"text":"UIInterfaceOrientationMask","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIInterfaceOrientationMask"}],"required":true,"abstract":[{"text":"Determines the supported interface orientations for the application.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"application:supportedInterfaceOrientationsForWindow:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraAppDelegate\/application(_:supportedInterfaceOrientationsFor:)","title":"application(_:supportedInterfaceOrientationsFor:)","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"TruvideoSdkCameraAppDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"TruvideoSdkCameraAppDelegate","kind":"identifier"}]},{"op":"replace","value":[{"text":"TruvideoSdkCameraAppDelegate","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraAppDelegate\/orientationLock"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"generated":true,"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraAppDelegate\/application(_:supportedInterfaceOrientationsFor:)"],"anchor":"Instance-Methods","title":"Instance Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/objc(pl)UIApplicationDelegate"],"type":"inheritsFrom","kind":"relationships"}]},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraAppDelegate","kind":"identifier"},{"text":" <","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIApplicationDelegate","text":"UIApplicationDelegate"},{"text":">","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraAppDelegate~1orientationLock\/title","value":"orientationLock"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraAppDelegate~1orientationLock\/fragments","value":[{"text":"orientationLock","kind":"identifier"}]},{"op":"replace","value":"TruvideoSdkCameraAppDelegate","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraAppDelegate\/title"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraAppDelegate\/fragments","value":[{"text":"TruvideoSdkCameraAppDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraAppDelegate\/navigatorTitle","value":[{"text":"TruvideoSdkCameraAppDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"application:supportedInterfaceOrientationsForWindow:","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraAppDelegate~1application(_:supportedInterfaceOrientationsFor:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"application:supportedInterfaceOrientationsForWindow:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraAppDelegate~1application(_:supportedInterfaceOrientationsFor:)\/fragments"}]}]}