{"abstract":[{"type":"text","text":"Triggered when media capture is successfully completed."}],"variants":[{"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameraeventtype\/truvideosdkcameraeventmediacontinue(media:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraEventType"]]},"kind":"symbol","metadata":{"title":"TruvideoSdkCameraEventType.truvideoSdkCameraEventMediaContinue(media:)","externalID":"s:17TruvideoSdkCamera0abC9EventTypeO08truvideobcD13MediaContinueyACSayAA0abcG0CG_tcACmF","modules":[{"name":"TruvideoSdkCamera"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"truvideoSdkCameraEventMediaContinue"},{"text":"(","kind":"text"},{"text":"media","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"TruvideoSdkCameraMedia","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraMedia","kind":"typeIdentifier"},{"kind":"text","text":"])"}],"roleHeading":"Case","symbolKind":"case"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraEventType\/truvideoSdkCameraEventMediaContinue(media:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"truvideoSdkCameraEventMediaContinue"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"media"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMedia","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraMedia","text":"TruvideoSdkCameraMedia","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The list of captured media.","type":"text"}]}],"name":"media"}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"This event fires when the camera session "},{"type":"strong","inlineContent":[{"type":"text","text":"continues"}]},{"type":"text","text":" and media is recorded."}],"type":"paragraph"}]}],"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraMedia":{"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TruvideoSdkCameraMedia","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameramedia","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraMedia"}],"type":"topic","title":"TruvideoSdkCameraMedia","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMedia","kind":"symbol","role":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraEventType/truvideoSdkCameraEventMediaContinue(media:)":{"abstract":[{"type":"text","text":"Triggered when media capture is successfully completed."}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraeventtype\/truvideosdkcameraeventmediacontinue(media:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraEventType\/truvideoSdkCameraEventMediaContinue(media:)","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"truvideoSdkCameraEventMediaContinue"},{"kind":"text","text":"("},{"kind":"externalParam","text":"media"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraMedia","text":"TruvideoSdkCameraMedia","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"title":"TruvideoSdkCameraEventType.truvideoSdkCameraEventMediaContinue(media:)","type":"topic"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"type":"topic","title":"TruvideoSdkCamera","url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}],"kind":"symbol","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraEventType":{"navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraEventType"}],"role":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraEventType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraEventType"}],"title":"TruvideoSdkCameraEventType","abstract":[{"text":"Defines the different types of events emitted by ","type":"text"},{"type":"codeVoice","code":"TruvideoSdkCamera"},{"text":".","type":"text"}],"type":"topic","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraeventtype","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"TruvideoSdkCameraMedia","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMedia\/title"},{"value":[{"text":"TruvideoSdkCameraMedia","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMedia\/fragments"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMedia\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TruvideoSdkCameraMedia"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}