{"abstract":[{"text":"Triggered when the camera is flipped between ","type":"text"},{"inlineContent":[{"type":"text","text":"front-facing"}],"type":"strong"},{"text":" and ","type":"text"},{"inlineContent":[{"text":"rear-facing","type":"text"}],"type":"strong"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraEventType"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"truvideoSdkCameraEventCameraFlipped","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"lensFacing"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TruvideoSdkCameraLensFacing","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraLensFacing","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraLensFacing"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The new lens direction (","type":"text"},{"type":"codeVoice","code":".front"},{"text":", ","type":"text"},{"code":".back","type":"codeVoice"},{"type":"text","text":")."}],"type":"paragraph"}],"name":"lensFacing"}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameraeventtype\/truvideosdkcameraeventcameraflipped(lensfacing:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"metadata":{"symbolKind":"case","roleHeading":"Case","modules":[{"name":"TruvideoSdkCamera"}],"title":"TruvideoSdkCameraEventType.truvideoSdkCameraEventCameraFlipped(lensFacing:)","externalID":"s:17TruvideoSdkCamera0abC9EventTypeO08truvideobcdC7FlippedyAcA0abC10LensFacingO_tcACmF","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"truvideoSdkCameraEventCameraFlipped"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"lensFacing"},{"text":": ","kind":"text"},{"text":"TruvideoSdkCameraLensFacing","kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraLensFacing"},{"text":")","kind":"text"}]},"identifier":{"url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraEventType\/truvideoSdkCameraEventCameraFlipped(lensFacing:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraLensFacing":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraLensFacing","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraLensFacing"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TruvideoSdkCameraLensFacing"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameralensfacing","role":"symbol","abstract":[{"text":"Defines the camera lens direction used for capturing media.","type":"text"}],"title":"TruvideoSdkCameraLensFacing","kind":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraEventType/truvideoSdkCameraEventCameraFlipped(lensFacing:)":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraEventType\/truvideoSdkCameraEventCameraFlipped(lensFacing:)","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraeventtype\/truvideosdkcameraeventcameraflipped(lensfacing:)","type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"Triggered when the camera is flipped between ","type":"text"},{"type":"strong","inlineContent":[{"text":"front-facing","type":"text"}]},{"type":"text","text":" and "},{"inlineContent":[{"type":"text","text":"rear-facing"}],"type":"strong"},{"text":".","type":"text"}],"title":"TruvideoSdkCameraEventType.truvideoSdkCameraEventCameraFlipped(lensFacing:)","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"truvideoSdkCameraEventCameraFlipped"},{"kind":"text","text":"("},{"text":"lensFacing","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TruvideoSdkCameraLensFacing","preciseIdentifier":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraLensFacing"},{"kind":"text","text":")"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"type":"topic","title":"TruvideoSdkCamera","url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}],"kind":"symbol","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraEventType":{"navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraEventType"}],"role":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraEventType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraEventType"}],"title":"TruvideoSdkCameraEventType","abstract":[{"text":"Defines the different types of events emitted by ","type":"text"},{"type":"codeVoice","code":"TruvideoSdkCamera"},{"text":".","type":"text"}],"type":"topic","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraeventtype","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraLensFacing\/title","value":"TruvideoSdkCameraLensFacing"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraLensFacing\/fragments","op":"replace","value":[{"text":"TruvideoSdkCameraLensFacing","kind":"identifier"}]},{"value":[{"text":"TruvideoSdkCameraLensFacing","kind":"identifier"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraLensFacing\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}