{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraEventType"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraEventType\/truvideoSdkCameraEventMediaDiscard(media:)"},"variants":[{"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameraeventtype\/truvideosdkcameraeventmediadiscard(media:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","metadata":{"role":"symbol","symbolKind":"case","modules":[{"name":"TruvideoSdkCamera"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"truvideoSdkCameraEventMediaDiscard","kind":"identifier"},{"text":"(","kind":"text"},{"text":"media","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraMedia","kind":"typeIdentifier","text":"TruvideoSdkCameraMedia"},{"kind":"text","text":"])"}],"title":"TruvideoSdkCameraEventType.truvideoSdkCameraEventMediaDiscard(media:)","externalID":"s:17TruvideoSdkCamera0abC9EventTypeO08truvideobcD12MediaDiscardyACSayAA0abcG0CG_tcACmF","roleHeading":"Case"},"abstract":[{"text":"Triggered when media is ","type":"text"},{"inlineContent":[{"text":"discarded","type":"text"}],"type":"strong"},{"text":" after closing the camera.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"truvideoSdkCameraEventMediaDiscard"},{"kind":"text","text":"("},{"kind":"externalParam","text":"media"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMedia","text":"TruvideoSdkCameraMedia","kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraMedia"},{"kind":"text","text":"])"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"media","content":[{"inlineContent":[{"type":"text","text":"The list of discarded media."}],"type":"paragraph"}]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraMedia":{"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TruvideoSdkCameraMedia","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameramedia","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraMedia"}],"type":"topic","title":"TruvideoSdkCameraMedia","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraMedia","kind":"symbol","role":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraEventType":{"navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraEventType"}],"role":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraEventType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraEventType"}],"title":"TruvideoSdkCameraEventType","abstract":[{"text":"Defines the different types of events emitted by ","type":"text"},{"type":"codeVoice","code":"TruvideoSdkCamera"},{"text":".","type":"text"}],"type":"topic","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraeventtype","kind":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"type":"topic","title":"TruvideoSdkCamera","url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}],"kind":"symbol","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraEventType/truvideoSdkCameraEventMediaDiscard(media:)":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraEventType\/truvideoSdkCameraEventMediaDiscard(media:)","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraeventtype\/truvideosdkcameraeventmediadiscard(media:)","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"truvideoSdkCameraEventMediaDiscard"},{"text":"(","kind":"text"},{"text":"media","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"TruvideoSdkCameraMedia","kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraMedia"},{"kind":"text","text":"])"}],"role":"symbol","title":"TruvideoSdkCameraEventType.truvideoSdkCameraEventMediaDiscard(media:)","kind":"symbol","abstract":[{"text":"Triggered when media is ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"discarded"}]},{"type":"text","text":" after closing the camera."}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"TruvideoSdkCameraMedia","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMedia\/title"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMedia\/fragments","value":[{"kind":"identifier","text":"TruvideoSdkCameraMedia"}],"op":"replace"},{"op":"replace","value":[{"text":"TruvideoSdkCameraMedia","kind":"identifier"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraMedia\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}