{"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDevice"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"encode","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":" "},{"text":"encoder","kind":"internalParam"},{"kind":"text","text":": "},{"text":"any","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:s7EncoderP","text":"Encoder"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"platforms":["iOS"]}]}],"sections":[],"metadata":{"roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"TruvideoSdkCamera"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"encode","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"any","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Encoder","preciseIdentifier":"s:s7EncoderP"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"title":"encode(to:)","externalID":"s:17TruvideoSdkCamera0abC6DeviceC6encode2toys7Encoder_p_tKF","role":"symbol"},"identifier":{"url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDevice\/encode(to:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Encodable.encode(to:)"},{"type":"text","text":"."}],"kind":"symbol","variants":[{"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameradevice\/encode(to:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraDevice/encode(to:)":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDevice\/encode(to:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"encode","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"keyword","text":"any"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:s7EncoderP","text":"Encoder","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameradevice\/encode(to:)","title":"encode(to:)","abstract":[],"role":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraDevice":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraDevice","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameradevice","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraDevice","abstract":[{"text":"Represents a camera device available on the system.","type":"text"}],"title":"TruvideoSdkCameraDevice","navigatorTitle":[{"text":"TruvideoSdkCameraDevice","kind":"identifier"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"type":"topic","title":"TruvideoSdkCamera","url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}],"kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraDevice\/title","op":"replace","value":"TruvideoSdkCameraDevice"},{"value":[{"text":"TruvideoSdkCameraDevice","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraDevice\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraDevice\/navigatorTitle","value":[{"text":"TruvideoSdkCameraDevice","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}