{"variants":[{"paths":["\/documentation\/truvideosdkcamera\/kbufferindexmeshpositions"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/truvideosdkcamera\/kbufferindexmeshpositions"]}],"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera"],["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/BufferIndices"]]},"kind":"symbol","metadata":{"roleHeading":"Global Variable","title":"kBufferIndexMeshPositions","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"kBufferIndexMeshPositions","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"BufferIndices","preciseIdentifier":"c:@E@BufferIndices"}],"role":"symbol","symbolKind":"var","externalID":"c:@E@BufferIndices@kBufferIndexMeshPositions","modules":[{"name":"TruvideoSdkCamera"}],"navigatorTitle":[{"kind":"identifier","text":"kBufferIndexMeshPositions"}]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"kBufferIndexMeshPositions","kind":"identifier"},{"text":": ","kind":"text"},{"text":"BufferIndices","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/BufferIndices","kind":"typeIdentifier","preciseIdentifier":"c:@E@BufferIndices"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kBufferIndexMeshPositions"},"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"type":"topic","title":"TruvideoSdkCamera","url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}],"kind":"symbol","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/kBufferIndexMeshPositions":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"kBufferIndexMeshPositions","kind":"identifier"},{"kind":"text","text":": "},{"text":"BufferIndices","kind":"typeIdentifier","preciseIdentifier":"c:@E@BufferIndices"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kBufferIndexMeshPositions","kind":"symbol","title":"kBufferIndexMeshPositions","navigatorTitle":[{"text":"kBufferIndexMeshPositions","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/kbufferindexmeshpositions"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/BufferIndices":{"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"BufferIndices","kind":"identifier"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/BufferIndices","kind":"symbol","title":"BufferIndices","navigatorTitle":[{"kind":"identifier","text":"BufferIndices"}],"url":"\/documentation\/truvideosdkcamera\/bufferindices"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"kBufferIndexMeshPositions"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"kBufferIndexMeshPositions","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"kBufferIndexMeshPositions","kind":"identifier"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1kBufferIndexMeshPositions\/title","op":"replace","value":"kBufferIndexMeshPositions"},{"value":[{"kind":"identifier","text":"kBufferIndexMeshPositions"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1kBufferIndexMeshPositions\/fragments"},{"value":"BufferIndices","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1BufferIndices\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1BufferIndices\/fragments","value":[{"text":"BufferIndices","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1BufferIndices\/navigatorTitle","value":[{"text":"BufferIndices","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}