{"relationshipsSections":[{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/s15BitwiseCopyableP","doc:\/\/com.truvideo.TruvideoSdkCamera\/SQ","doc:\/\/com.truvideo.TruvideoSdkCamera\/SY","doc:\/\/com.truvideo.TruvideoSdkCamera\/s8SendableP"],"title":"Conforms To"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TextureIndices"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/truvideosdkcamera\/textureindices"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/truvideosdkcamera\/textureindices"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TextureIndices"},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:@E@TextureIndices","modules":[{"name":"TruvideoSdkCamera"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TextureIndices"}],"roleHeading":"Structure","title":"TextureIndices","symbolKind":"struct","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TextureIndices"}]},"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera"]]},"sections":[],"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TextureIndices\/init(_:)","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TextureIndices\/init(rawValue:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TextureIndices\/rawValue"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TextureIndices\/Equatable-Implementations"],"generated":true,"anchor":"Default-Implementations"}],"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TextureIndices":{"kind":"symbol","abstract":[],"role":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TextureIndices","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"TextureIndices","kind":"identifier"}],"title":"TextureIndices","navigatorTitle":[{"kind":"identifier","text":"TextureIndices"}],"type":"topic","url":"\/documentation\/truvideosdkcamera\/textureindices"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TextureIndices/rawValue":{"title":"rawValue","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"rawValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt32","preciseIdentifier":"s:s6UInt32V","kind":"typeIdentifier"}],"url":"\/documentation\/truvideosdkcamera\/textureindices\/rawvalue","type":"topic","kind":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TextureIndices\/rawValue"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TextureIndices/init(_:)":{"type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V","text":"UInt32"},{"text":")","kind":"text"}],"title":"init(_:)","kind":"symbol","role":"symbol","url":"\/documentation\/truvideosdkcamera\/textureindices\/init(_:)","abstract":[],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TextureIndices\/init(_:)"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/kTextureIndexY":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"kTextureIndexY","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TextureIndices","preciseIdentifier":"c:@E@TextureIndices"}],"navigatorTitle":[{"kind":"identifier","text":"kTextureIndexY"}],"title":"kTextureIndexY","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kTextureIndexY","type":"topic","abstract":[],"url":"\/documentation\/truvideosdkcamera\/ktextureindexy"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TextureIndices/Equatable-Implementations":{"url":"\/documentation\/truvideosdkcamera\/textureindices\/equatable-implementations","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TextureIndices\/Equatable-Implementations","type":"topic","kind":"article","role":"collectionGroup","abstract":[],"title":"Equatable Implementations"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/kTextureIndexRGB":{"role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kTextureIndexRGB"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@TextureIndices","kind":"typeIdentifier","text":"TextureIndices"}],"navigatorTitle":[{"kind":"identifier","text":"kTextureIndexRGB"}],"title":"kTextureIndexRGB","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kTextureIndexRGB","type":"topic","abstract":[],"url":"\/documentation\/truvideosdkcamera\/ktextureindexrgb"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TextureIndices/init(rawValue:)":{"url":"\/documentation\/truvideosdkcamera\/textureindices\/init(rawvalue:)","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TextureIndices\/init(rawValue:)","type":"topic","kind":"symbol","role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"text":"UInt32","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V"},{"text":")","kind":"text"}],"abstract":[]},"doc://com.truvideo.TruvideoSdkCamera/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/s8SendableP"},"doc://com.truvideo.TruvideoSdkCamera/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/SQ"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/kTextureIndexCbCr":{"title":"kTextureIndexCbCr","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kTextureIndexCbCr","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"kTextureIndexCbCr","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TextureIndices","preciseIdentifier":"c:@E@TextureIndices","kind":"typeIdentifier"}],"url":"\/documentation\/truvideosdkcamera\/ktextureindexcbcr","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kTextureIndexCbCr"}],"abstract":[]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/kTextureIndexColor":{"type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"kTextureIndexColor","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@TextureIndices","text":"TextureIndices"}],"url":"\/documentation\/truvideosdkcamera\/ktextureindexcolor","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kTextureIndexColor","role":"symbol","navigatorTitle":[{"text":"kTextureIndexColor","kind":"identifier"}],"kind":"symbol","title":"kTextureIndexColor"},"doc://com.truvideo.TruvideoSdkCamera/s15BitwiseCopyableP":{"type":"unresolvable","title":"Swift.BitwiseCopyable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/s15BitwiseCopyableP"},"doc://com.truvideo.TruvideoSdkCamera/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/SY"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"type":"topic","title":"TruvideoSdkCamera","url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}],"kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"TextureIndices"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"TextureIndices"}]},{"op":"replace","value":[{"text":"TextureIndices","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kTextureIndexCbCr","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kTextureIndexColor","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kTextureIndexRGB","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/kTextureIndexY"],"anchor":"Enumeration-Cases","generated":true}],"op":"replace","path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TextureIndices"},{"kind":"text","text":": "},{"text":"unsigned int","kind":"typeIdentifier","preciseIdentifier":"c:i"},{"text":" { ... } ","kind":"text"},{"kind":"identifier","text":"TextureIndices"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"TextureIndices","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TextureIndices\/title","op":"replace"},{"value":[{"kind":"identifier","text":"TextureIndices"}],"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TextureIndices\/fragments"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TextureIndices\/navigatorTitle","value":[{"kind":"identifier","text":"TextureIndices"}],"op":"replace"},{"value":"kTextureIndexY","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1kTextureIndexY\/title","op":"replace"},{"op":"replace","value":[{"text":"kTextureIndexY","kind":"identifier"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1kTextureIndexY\/fragments"},{"op":"replace","value":"kTextureIndexRGB","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1kTextureIndexRGB\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1kTextureIndexRGB\/fragments","value":[{"text":"kTextureIndexRGB","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1kTextureIndexCbCr\/title","value":"kTextureIndexCbCr"},{"value":[{"kind":"identifier","text":"kTextureIndexCbCr"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1kTextureIndexCbCr\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1kTextureIndexColor\/title","value":"kTextureIndexColor"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1kTextureIndexColor\/fragments","op":"replace","value":[{"kind":"identifier","text":"kTextureIndexColor"}]}]}]}