{"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerValidation"},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"A function signature for validating scanned barcodes.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcamerascannervalidation"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TruvideoSdkCameraScannerValidation"},{"kind":"text","text":" = ("},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraScannerCode","text":"TruvideoSdkCameraScannerCode","kind":"typeIdentifier","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCode"},{"kind":"text","text":") -> "},{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerValidationResult","text":"TruvideoSdkCameraScannerValidationResult","kind":"typeIdentifier","preciseIdentifier":"s:17TruvideoSdkCamera0abC23ScannerValidationResultV"}]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The scanned barcode data."}]}],"name":"code"}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"A validation result indicating success or failure."}],"type":"paragraph"}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"inlineContent":[{"text":"This typealias defines a ","type":"text"},{"inlineContent":[{"text":"validation function","type":"text"}],"type":"strong"},{"text":" that determines whether a scanned barcode is valid.","type":"text"}],"type":"paragraph"},{"level":2,"text":"Example Usage","type":"heading","anchor":"Example-Usage"},{"syntax":"swift","code":["let validation: TruvideoSdkCameraScannerValidation = { code in","    return code.rawValue.contains(\"TRU\") ? .success() : .fail(message: \"Invalid format\")","}"],"type":"codeListing"}]}],"metadata":{"role":"symbol","roleHeading":"Type Alias","modules":[{"name":"TruvideoSdkCamera"}],"symbolKind":"typealias","title":"TruvideoSdkCameraScannerValidation","externalID":"s:17TruvideoSdkCamera0abC17ScannerValidationa","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TruvideoSdkCameraScannerValidation"}],"navigatorTitle":[{"text":"TruvideoSdkCameraScannerValidation","kind":"identifier"}]},"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"type":"topic","title":"TruvideoSdkCamera","url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}],"kind":"symbol","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraScannerValidationResult":{"url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerascannervalidationresult","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraScannerValidationResult","kind":"identifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerValidationResult","abstract":[{"text":"Represents the result of a barcode validation process.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"TruvideoSdkCameraScannerValidationResult","kind":"identifier"}],"kind":"symbol","title":"TruvideoSdkCameraScannerValidationResult","role":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraScannerValidation":{"title":"TruvideoSdkCameraScannerValidation","type":"topic","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerValidation","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraScannerValidation"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerascannervalidation","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraScannerValidation"}],"abstract":[{"text":"A function signature for validating scanned barcodes.","type":"text"}],"role":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraScannerCode":{"url":"\/documentation\/truvideosdkcamera\/truvideosdkcamerascannercode","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkCameraScannerCode"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraScannerCode","abstract":[{"text":"Represents the result of a barcode or QR code scan.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraScannerCode"}],"kind":"symbol","title":"TruvideoSdkCameraScannerCode","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraScannerCode\/title","value":"TruvideoSdkCameraScannerCode","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraScannerCode\/fragments","value":[{"kind":"identifier","text":"TruvideoSdkCameraScannerCode"}]},{"value":[{"text":"TruvideoSdkCameraScannerCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraScannerCode\/navigatorTitle","op":"replace"}]}]}