{"sections":[],"metadata":{"externalID":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResolution","role":"symbol","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TruvideoSdkCameraResolution"}],"title":"TruvideoSdkCameraResolution","modules":[{"name":"TruvideoSdkCamera"}],"symbolKind":"class","navigatorTitle":[{"text":"TruvideoSdkCameraResolution","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera"]]},"variants":[{"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameraresolution"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameraresolution"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResolution"},"kind":"symbol","topicSections":[{"title":"Operators","anchor":"Operators","generated":true,"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResolution\/==(_:_:)","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResolution\/_(_:_:)-3o792"]},{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResolution\/init(from:)","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResolution\/init(width:height:)"],"generated":true},{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResolution\/height","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResolution\/width"],"title":"Instance Properties"},{"title":"Default Implementations","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResolution\/Comparable-Implementations"],"generated":true,"anchor":"Default-Implementations"}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/objc(pl)NSObject","doc:\/\/com.truvideo.TruvideoSdkCamera\/s7CVarArgP","doc:\/\/com.truvideo.TruvideoSdkCamera\/SL","doc:\/\/com.truvideo.TruvideoSdkCamera\/s28CustomDebugStringConvertibleP","doc:\/\/com.truvideo.TruvideoSdkCamera\/s23CustomStringConvertibleP","doc:\/\/com.truvideo.TruvideoSdkCamera\/SE","doc:\/\/com.truvideo.TruvideoSdkCamera\/SQ","doc:\/\/com.truvideo.TruvideoSdkCamera\/SH"],"title":"Conforms To"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TruvideoSdkCameraResolution","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraResolution/Comparable-Implementations":{"type":"topic","role":"collectionGroup","title":"Comparable Implementations","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraresolution\/comparable-implementations","abstract":[],"kind":"article","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResolution\/Comparable-Implementations"},"doc://com.truvideo.TruvideoSdkCamera/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraResolution/height":{"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraresolution\/height","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"height","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"}],"navigatorTitle":[{"kind":"identifier","text":"height"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResolution\/height","kind":"symbol","type":"topic","role":"symbol","title":"height","abstract":[]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraResolution/init(from:)":{"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraresolution\/init(from:)","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResolution\/init(from:)","type":"topic","kind":"symbol","role":"symbol","abstract":[],"title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP","text":"Decoder"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}]},"doc://com.truvideo.TruvideoSdkCamera/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/SQ"},"doc://com.truvideo.TruvideoSdkCamera/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/objc(cs)NSObject"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraResolution":{"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraresolution","type":"topic","kind":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResolution","navigatorTitle":[{"text":"TruvideoSdkCameraResolution","kind":"identifier"}],"title":"TruvideoSdkCameraResolution","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TruvideoSdkCameraResolution","kind":"identifier"}]},"doc://com.truvideo.TruvideoSdkCamera/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/SH"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraResolution/width":{"title":"width","type":"topic","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"width","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResolution\/width","kind":"symbol","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraresolution\/width","navigatorTitle":[{"text":"width","kind":"identifier"}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraResolution/_(_:_:)-3o792":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResolution\/_(_:_:)-3o792","role":"symbol","title":"<(_:_:)","abstract":[],"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"<","kind":"identifier"},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TruvideoSdkCameraResolution","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResolution"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResolution","text":"TruvideoSdkCameraResolution","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraresolution\/_(_:_:)-3o792","kind":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraResolution/==(_:_:)":{"role":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResolution\/==(_:_:)","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"==","kind":"identifier"},{"kind":"text","text":" "},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResolution","kind":"typeIdentifier","text":"TruvideoSdkCameraResolution"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResolution","text":"TruvideoSdkCameraResolution"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraresolution\/==(_:_:)","kind":"symbol","title":"==(_:_:)"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"type":"topic","title":"TruvideoSdkCamera","url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}],"kind":"symbol","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/objc(pl)NSObject"},"doc://com.truvideo.TruvideoSdkCamera/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/s7CVarArgP"},"doc://com.truvideo.TruvideoSdkCamera/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/s28CustomDebugStringConvertibleP"},"doc://com.truvideo.TruvideoSdkCamera/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/SE"},"doc://com.truvideo.TruvideoSdkCamera/SL":{"type":"unresolvable","title":"Swift.Comparable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/SL"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraResolution/init(width:height:)":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResolution\/init(width:height:)","kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"width","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"height"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":")"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraresolution\/init(width:height:)","navigatorTitle":[{"text":"initWithWidth:height:","kind":"identifier"}],"type":"topic","title":"init(width:height:)","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"TruvideoSdkCameraResolution"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"kind":"identifier","text":"TruvideoSdkCameraResolution"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"TruvideoSdkCameraResolution"}],"op":"replace"},{"value":[{"generated":true,"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResolution\/height","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResolution\/width"],"anchor":"Instance-Properties","title":"Instance Properties"},{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResolution\/init(width:height:)"]}],"op":"replace","path":"\/topicSections"},{"value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"}],"path":"\/relationshipsSections","op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"TruvideoSdkCameraResolution","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResolution~1height\/title","value":"height"},{"op":"replace","value":[{"text":"height","kind":"identifier"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResolution~1height\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResolution\/title","value":"TruvideoSdkCameraResolution"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResolution\/fragments","value":[{"kind":"identifier","text":"TruvideoSdkCameraResolution"}]},{"op":"replace","value":[{"text":"TruvideoSdkCameraResolution","kind":"identifier"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResolution\/navigatorTitle"},{"value":"width","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResolution~1width\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"width"}],"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResolution~1width\/fragments"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResolution~1init(width:height:)\/title","value":"initWithWidth:height:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResolution~1init(width:height:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithWidth:height:"}]}]}]}