{"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TruvideoSdkCameraProvider"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"anchor":"overview","type":"heading","text":"Overview","level":2},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"TruvideoSdkCameraProvider"},{"text":" acts as a singleton, offering a centralized way to access the ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"Truvideo Camera SDK"}]},{"type":"text","text":"."}]},{"text":"Example Usage","level":2,"type":"heading","anchor":"Example-Usage"},{"type":"codeListing","code":["let cameraInstance = TruvideoSdkCameraProvider.shared","let cameraInfo = cameraInstance.getTruvideoSdkCameraInformation()"],"syntax":"swift"}],"kind":"content"}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/objc(pl)NSObject","doc:\/\/com.truvideo.TruvideoSdkCamera\/s7CVarArgP","doc:\/\/com.truvideo.TruvideoSdkCamera\/s28CustomDebugStringConvertibleP","doc:\/\/com.truvideo.TruvideoSdkCamera\/s23CustomStringConvertibleP","doc:\/\/com.truvideo.TruvideoSdkCamera\/SQ","doc:\/\/com.truvideo.TruvideoSdkCamera\/SH"],"kind":"relationships"}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraProvider\/shared"],"anchor":"Type-Properties","title":"Type Properties"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameraprovider"]},{"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameraprovider"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"symbol","roleHeading":"Class","title":"TruvideoSdkCameraProvider","externalID":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraProvider","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TruvideoSdkCameraProvider","kind":"identifier"}],"modules":[{"name":"TruvideoSdkCamera"}],"symbolKind":"class","navigatorTitle":[{"text":"TruvideoSdkCameraProvider","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraProvider"},"abstract":[{"type":"text","text":"Provides a shared instance for accessing "},{"code":"TruvideoSdkCamera","type":"codeVoice"},{"type":"text","text":" functionalities."}],"references":{"doc://com.truvideo.TruvideoSdkCamera/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/SH"},"doc://com.truvideo.TruvideoSdkCamera/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/SQ"},"doc://com.truvideo.TruvideoSdkCamera/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/objc(pl)NSObject"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"type":"topic","title":"TruvideoSdkCamera","url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}],"kind":"symbol","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.truvideo.TruvideoSdkCamera/s7CVarArgP":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.truvideo.TruvideoSdkCamera/objc(cs)NSObject":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraProvider/shared":{"title":"shared","navigatorTitle":[{"text":"shared","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraProvider\/shared","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraprovider\/shared","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TruvideoSdkCameraInterface","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(pl)TruvideoSdkCameraInterface"}],"kind":"symbol","abstract":[{"type":"text","text":"The shared instance for accessing "},{"type":"codeVoice","code":"TruvideoSdkCamera"},{"type":"text","text":" functionalities."}]},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraProvider":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"TruvideoSdkCameraProvider","kind":"identifier"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraProvider","kind":"identifier"}],"title":"TruvideoSdkCameraProvider","abstract":[{"type":"text","text":"Provides a shared instance for accessing "},{"type":"codeVoice","code":"TruvideoSdkCamera"},{"text":" functionalities.","type":"text"}],"kind":"symbol","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraprovider"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraProvider/init":{"abstract":[],"kind":"symbol","role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"type":"topic","url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraprovider\/init","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraProvider\/init"},"doc://com.truvideo.TruvideoSdkCamera/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"TruvideoSdkCameraProvider"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"TruvideoSdkCameraProvider","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TruvideoSdkCameraProvider"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraProvider\/init"],"anchor":"Instance-Methods","title":"Instance Methods"},{"title":"Type Properties","anchor":"Type-Properties","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraProvider\/shared"],"generated":true}]},{"op":"replace","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.truvideo.TruvideoSdkCamera\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"}],"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"TruvideoSdkCameraProvider","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","value":"shared","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraProvider~1shared\/title"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraProvider~1shared\/fragments","op":"replace","value":[{"kind":"identifier","text":"shared"}]},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraProvider\/title","op":"replace","value":"TruvideoSdkCameraProvider"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraProvider\/fragments","value":[{"text":"TruvideoSdkCameraProvider","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraProvider\/navigatorTitle","value":[{"text":"TruvideoSdkCameraProvider","kind":"identifier"}]}]}]}