{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"back"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"identifier":{"url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraLensFacing\/back","interfaceLanguage":"swift"},"abstract":[{"text":"Uses the rear-facing camera.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraLensFacing"]]},"metadata":{"role":"symbol","title":"TruvideoSdkCameraLensFacing.back","roleHeading":"Case","symbolKind":"case","navigatorTitle":[{"text":"TruvideoSdkCameraLensFacingBack","kind":"identifier"}],"externalID":"c:@M@TruvideoSdkCamera@E@TruvideoSdkCameraLensFacing@TruvideoSdkCameraLensFacingBack","modules":[{"name":"TruvideoSdkCamera"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"back"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameralensfacing\/back"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/truvideosdkcamera\/truvideosdkcameralensfacing\/back"]}],"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"type":"topic","title":"TruvideoSdkCamera","url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}],"kind":"symbol","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraLensFacing":{"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraLensFacing","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkCameraLensFacing"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TruvideoSdkCameraLensFacing"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameralensfacing","role":"symbol","abstract":[{"text":"Defines the camera lens direction used for capturing media.","type":"text"}],"title":"TruvideoSdkCameraLensFacing","kind":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraLensFacing/back":{"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameralensfacing\/back","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"back"}],"abstract":[{"type":"text","text":"Uses the rear-facing camera."}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraLensFacing\/back","kind":"symbol","title":"TruvideoSdkCameraLensFacing.back","navigatorTitle":[{"text":"TruvideoSdkCameraLensFacingBack","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"TruvideoSdkCameraLensFacingBack"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","value":[{"text":"TruvideoSdkCameraLensFacingBack","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"TruvideoSdkCameraLensFacingBack"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraLensFacing\/title","value":"TruvideoSdkCameraLensFacing"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraLensFacing\/fragments","value":[{"text":"TruvideoSdkCameraLensFacing","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraLensFacing\/navigatorTitle","value":[{"text":"TruvideoSdkCameraLensFacing","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraLensFacing~1back\/title","value":"TruvideoSdkCameraLensFacingBack","op":"replace"},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraLensFacing~1back\/fragments","value":[{"text":"TruvideoSdkCameraLensFacingBack","kind":"identifier"}],"op":"replace"}]}]}