{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/UIKit\/UIViewController\/presentTruvideoSdkARCameraView(preset:onComplete:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"presentTruvideoSdkARCameraView","kind":"identifier"},{"kind":"text","text":"("},{"text":"preset","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TruvideoSdkARCameraConfiguration","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkARCameraConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkARCameraConfiguration"},{"text":" = .init(flashMode: .off, mode: .videoAndPicture(), orientation: nil), ","kind":"text"},{"text":"onComplete","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResult","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResult","text":"TruvideoSdkCameraResult"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"preset","content":[{"inlineContent":[{"type":"text","text":"A "},{"code":"TruvideoSdkARCameraConfiguration","type":"codeVoice"},{"text":" object containing the AR camera configuration.","type":"text"}],"type":"paragraph"}]},{"name":"onComplete","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A callback function that receives a "},{"code":"TruvideoSdkCameraResult","type":"codeVoice"},{"text":" containing captured media.","type":"text"}]}]}]},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"inlineContent":[{"type":"text","text":"The camera view is presented "},{"type":"strong","inlineContent":[{"type":"text","text":"modally in full screen"}]},{"text":", and once the session ends, the result is passed back to the caller.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"kind":"symbol","sections":[],"abstract":[{"text":"Presents the AR camera view over the full screen.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/UIKit","doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/UIKit\/UIViewController"]]},"metadata":{"extendedModule":"UIKit","externalID":"c:@CM@TruvideoSdkCamera@@objc(cs)UIViewController(im)presentTruvideoSdkARCameraViewWithPreset:onComplete:","modules":[{"name":"TruvideoSdkCamera","relatedModules":["UIKit"]}],"roleHeading":"Instance Method","role":"symbol","title":"presentTruvideoSdkARCameraView(preset:onComplete:)","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"presentTruvideoSdkARCameraView","kind":"identifier"},{"kind":"text","text":"("},{"text":"preset","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TruvideoSdkARCameraConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkARCameraConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"onComplete"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResult","kind":"typeIdentifier","text":"TruvideoSdkCameraResult"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}]},"variants":[{"paths":["\/documentation\/truvideosdkcamera\/uikit\/uiviewcontroller\/presenttruvideosdkarcameraview(preset:oncomplete:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/UIKit":{"abstract":[],"kind":"symbol","url":"\/documentation\/truvideosdkcamera\/uikit","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/UIKit","type":"topic","title":"UIKit","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/UIKit/UIViewController/presentTruvideoSdkARCameraView(preset:onComplete:)":{"url":"\/documentation\/truvideosdkcamera\/uikit\/uiviewcontroller\/presenttruvideosdkarcameraview(preset:oncomplete:)","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Presents the AR camera view over the full screen."}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/UIKit\/UIViewController\/presentTruvideoSdkARCameraView(preset:onComplete:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"presentTruvideoSdkARCameraView","kind":"identifier"},{"kind":"text","text":"("},{"text":"preset","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TruvideoSdkARCameraConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkARCameraConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"onComplete"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TruvideoSdkCamera@objc(cs)TruvideoSdkCameraResult","text":"TruvideoSdkCameraResult"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"title":"presentTruvideoSdkARCameraView(preset:onComplete:)"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkARCameraConfiguration":{"role":"symbol","url":"\/documentation\/truvideosdkcamera\/truvideosdkarcameraconfiguration","navigatorTitle":[{"kind":"identifier","text":"TruvideoSdkARCameraConfiguration"}],"title":"TruvideoSdkARCameraConfiguration","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkARCameraConfiguration","abstract":[{"text":"A configuration object for setting up the AR Camera in ","type":"text"},{"code":"TruvideoSdkCamera","type":"codeVoice"},{"text":".","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TruvideoSdkARCameraConfiguration"}],"kind":"symbol"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera":{"type":"topic","title":"TruvideoSdkCamera","url":"\/documentation\/truvideosdkcamera","identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera","abstract":[{"text":"Store and capture photos and videos using a fully integrated camera system.","type":"text"}],"kind":"symbol","role":"collection"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/TruvideoSdkCameraResult":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TruvideoSdkCameraResult","kind":"identifier"}],"role":"symbol","abstract":[{"text":"A result of the recording session.","type":"text"}],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/TruvideoSdkCameraResult","kind":"symbol","title":"TruvideoSdkCameraResult","navigatorTitle":[{"text":"TruvideoSdkCameraResult","kind":"identifier"}],"url":"\/documentation\/truvideosdkcamera\/truvideosdkcameraresult"},"doc://com.truvideo.TruvideoSdkCamera/documentation/TruvideoSdkCamera/UIKit/UIViewController":{"navigatorTitle":[{"kind":"identifier","text":"UIViewController"}],"url":"\/documentation\/truvideosdkcamera\/uikit\/uiviewcontroller","title":"UIViewController","type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/com.truvideo.TruvideoSdkCamera\/documentation\/TruvideoSdkCamera\/UIKit\/UIViewController","kind":"symbol","fragments":[{"text":"extension","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"TruvideoSdkARCameraConfiguration","op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkARCameraConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkARCameraConfiguration\/fragments","value":[{"text":"TruvideoSdkARCameraConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkARCameraConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"TruvideoSdkARCameraConfiguration"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResult\/title","value":"TruvideoSdkCameraResult"},{"op":"replace","path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResult\/fragments","value":[{"kind":"identifier","text":"TruvideoSdkCameraResult"}]},{"path":"\/references\/doc:~1~1com.truvideo.TruvideoSdkCamera~1documentation~1TruvideoSdkCamera~1TruvideoSdkCameraResult\/navigatorTitle","value":[{"text":"TruvideoSdkCameraResult","kind":"identifier"}],"op":"replace"}]}]}