{"topicSections":[{"identifiers":["doc:\/\/com.truvideo.TruvideoSdk\/documentation\/TruvideoSdk\/TruvideoSdkInterface"],"title":"Protocols"},{"title":"Variables","identifiers":["doc:\/\/com.truvideo.TruvideoSdk\/documentation\/TruvideoSdk\/TruvideoSdk"]},{"title":"Enumerations","identifiers":["doc:\/\/com.truvideo.TruvideoSdk\/documentation\/TruvideoSdk\/TruvideoSdkCoreError"]}],"primaryContentSections":[{"kind":"content","content":[{"level":2,"text":"Overview","anchor":"Overview","type":"heading"}]}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.truvideo.TruvideoSdk\/documentation\/TruvideoSdk","interfaceLanguage":"swift"},"hierarchy":{"paths":[[]]},"metadata":{"modules":[{"name":"TruvideoSdk"}],"role":"collection","roleHeading":"Framework","externalID":"TruvideoSdk","symbolKind":"module","title":"TruvideoSdk"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/truvideosdk"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/truvideosdk"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.truvideo.TruvideoSdk/documentation/TruvideoSdk/TruvideoSdkInterface":{"navigatorTitle":[{"text":"TruvideoSdkInterface","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"A protocol defining the interface for the Truvideo SDK, responsible for managing authentication"},{"type":"text","text":" "},{"text":"and providing essential SDK functionality.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TruvideoSdkInterface"}],"url":"\/documentation\/truvideosdk\/truvideosdkinterface","identifier":"doc:\/\/com.truvideo.TruvideoSdk\/documentation\/TruvideoSdk\/TruvideoSdkInterface","kind":"symbol","title":"TruvideoSdkInterface"},"doc://com.truvideo.TruvideoSdk/documentation/TruvideoSdk/TruvideoSdk":{"identifier":"doc:\/\/com.truvideo.TruvideoSdk\/documentation\/TruvideoSdk\/TruvideoSdk","type":"topic","title":"TruvideoSdk","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TruvideoSdk","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11TruvideoSdk0aB9InterfaceP","kind":"typeIdentifier","text":"TruvideoSdkInterface"}],"kind":"symbol","url":"\/documentation\/truvideosdk\/truvideosdk","abstract":[{"type":"text","text":"Constant used to expose the "},{"code":"TruvideoSdk","type":"codeVoice"},{"type":"text","text":" utilities"}]},"doc://com.truvideo.TruvideoSdk/documentation/TruvideoSdk":{"type":"topic","role":"collection","abstract":[],"title":"TruvideoSdk","kind":"symbol","identifier":"doc:\/\/com.truvideo.TruvideoSdk\/documentation\/TruvideoSdk","url":"\/documentation\/truvideosdk"},"doc://com.truvideo.TruvideoSdk/documentation/TruvideoSdk/TruvideoSdkVersionNumber":{"identifier":"doc:\/\/com.truvideo.TruvideoSdk\/documentation\/TruvideoSdk\/TruvideoSdkVersionNumber","type":"topic","title":"TruvideoSdkVersionNumber","role":"symbol","fragments":[{"text":"TruvideoSdkVersionNumber","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/truvideosdk\/truvideosdkversionnumber","abstract":[{"type":"text","text":"Project version number for TruvideoSdk."}]},"doc://com.truvideo.TruvideoSdk/documentation/TruvideoSdk/TruvideoSdkCoreError":{"abstract":[{"type":"text","text":"An enumeration representing the various errors that can occur within the Truvideo SDK core functionality."}],"identifier":"doc:\/\/com.truvideo.TruvideoSdk\/documentation\/TruvideoSdk\/TruvideoSdkCoreError","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"TruvideoSdkCoreError","kind":"identifier"}],"title":"TruvideoSdkCoreError","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TruvideoSdkCoreError","kind":"identifier"}],"url":"\/documentation\/truvideosdk\/truvideosdkcoreerror"},"doc://com.truvideo.TruvideoSdk/documentation/TruvideoSdk/TruvideoSdkVersionString":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Project version string for TruvideoSdk."}],"fragments":[{"text":"TruvideoSdkVersionString","kind":"identifier"}],"url":"\/documentation\/truvideosdk\/truvideosdkversionstring","identifier":"doc:\/\/com.truvideo.TruvideoSdk\/documentation\/TruvideoSdk\/TruvideoSdkVersionString","kind":"symbol","title":"TruvideoSdkVersionString"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":[{"title":"Variables","identifiers":["doc:\/\/com.truvideo.TruvideoSdk\/documentation\/TruvideoSdk\/TruvideoSdkVersionNumber","doc:\/\/com.truvideo.TruvideoSdk\/documentation\/TruvideoSdk\/TruvideoSdkVersionString"]}],"op":"replace"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"}]}]}