name: Unit Tests and Coverage
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4

      - name: Select Xcode Version
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: '16'

      - name: Resolve Package Dependencies
        run: swift package resolve

      - name: Install lcov and llvm-cov
        run: |
          brew install lcov llvm
          sudo ln -s /usr/local/opt/llvm/bin/llvm-cov /usr/local/bin/llvm-cov

      - name: Run Unit Tests (xcodebuild)
        run:  |
          xcodebuild test \
          -scheme 'TruvideoSdkFoundation' \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4' \
          -enableCodeCoverage YES \
          -resultBundlePath result.xcresult \
          -derivedDataPath build \
          -verbose